title: TaniaJekyll
description: Beautiful personal Jekyll theme
baseurl: "/TaniaJekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

title-separator: "-"

author:
  name: TaniaJekyll
  github: dinhanhthi
  facebook: math2it
  email: dinhanhthi@gmail.com


# Build settings
timezone: "Europe/Paris"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:categories/:title
# paginate: 24
# paginate_path: "/thought/page-:num"

# Facebook App ID
# fb_app_id: ""

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-feed
